services:
  backend:
    build: ./api
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/shipping_db
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
